import { StyleSheet } from 'react-native';
import { fonts, radii } from '@/theme/tokens';

/**
 * Layout-only styles for the Couple Dashboard's cards — no color values
 * live here. Every color comes from `useAppTheme()` at the JSX call site
 * instead (same split as the rest of the app, e.g. `profile/index.tsx`),
 * so switching the user's theme repaints this screen too.
 */
export const styles = StyleSheet.create({
  fill: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 14,
    justifyContent: 'space-between',
  },
  title: { fontFamily: fonts.bodyExtraBold, fontSize: 18, letterSpacing: -0.3, flex: 1, textAlign: 'center' },
  card: {
    marginHorizontal: 20,
    marginBottom: 14,
    padding: 16,
    borderRadius: radii.xl,
    gap: 8,
  },
  partnerRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  avatar: { width: 48, height: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center' },
  partnerName: { fontFamily: fonts.bodyExtraBold, fontSize: 16, letterSpacing: -0.2 },
  partnerRoleEmoji: { fontSize: 14 },
  partnerSub: { fontFamily: fonts.bodySemiBold, fontSize: 11, marginTop: 2 },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: radii.pill,
    borderWidth: 1,
  },
  statusDot: { width: 6, height: 6, borderRadius: 3 },
  statusPillText: { fontFamily: fonts.bodyExtraBold, fontSize: 11, letterSpacing: 0.4 },
  distanceRow: { paddingTop: 4 },
  distanceBig: { fontFamily: fonts.bodyExtraBold, fontSize: 36, letterSpacing: -1 },
  distanceSub: { fontFamily: fonts.bodySemiBold, fontSize: 12 },
  banner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: radii.md,
  },
  bannerText: { fontFamily: fonts.bodyBold, fontSize: 12, flexShrink: 1 },
  cardHeadRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline' },
  cardTitle: { fontFamily: fonts.bodyExtraBold, fontSize: 14, letterSpacing: -0.2 },
  cardSubtle: { fontFamily: fonts.bodySemiBold, fontSize: 11 },
  activeRow: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 10, borderRadius: radii.md, borderWidth: 1 },
  activeThumb: { width: 64, height: 80, borderRadius: radii.sm },
  activeTitle: { fontFamily: fonts.bodyExtraBold, fontSize: 14 },
  activeSub: { fontFamily: fonts.bodySemiBold, fontSize: 11 },
  activeEmpty: { justifyContent: 'flex-start' },
  activeEmptyText: { fontFamily: fonts.body, fontSize: 12, flex: 1 },
  packSectionLabel: { fontFamily: fonts.bodyBold, fontSize: 11.5, textTransform: 'uppercase', letterSpacing: 0.4, marginTop: 12, marginBottom: -2 },
  packGrid: { gap: 10 },
  packTile: { borderRadius: radii.md, borderWidth: 1, overflow: 'hidden' },
  packTileTriptych: { flexDirection: 'row', height: 88 },
  packTileSolo: { flex: 1, height: '100%' },
  packTileTogether: { flex: 1.4, height: '100%', borderLeftWidth: 1, borderRightWidth: 1 },
  packTileMeta: { paddingHorizontal: 10, paddingVertical: 8, gap: 2 },
  packTileName: { fontFamily: fonts.bodyExtraBold, fontSize: 13, letterSpacing: -0.2 },
  packTileBlurb: { fontFamily: fonts.body, fontSize: 10 },
  selectedDot: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  controlsRow: { flexDirection: 'row', gap: 10, paddingHorizontal: 20, marginBottom: 14 },
  ctrlBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
    borderRadius: radii.pill,
    borderWidth: 1,
  },
  ctrlBtnText: { fontFamily: fonts.bodyExtraBold, fontSize: 13 },
  privacyText: { fontFamily: fonts.body, fontSize: 11, lineHeight: 18, textAlign: 'center', paddingHorizontal: 20 },
  errText: { fontFamily: fonts.body, fontSize: 12, paddingHorizontal: 20, marginTop: 8 },
  emptyWrap: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 14 },
  emptyTitle: { fontFamily: fonts.bodyExtraBold, fontSize: 18 },
});
