/**
 * Generates src/data/sceneBriefs.ts — one text "scene brief" per template photo.
 * Run from server/: `node --env-file=.env node_modules/tsx/dist/cli.mjs scripts/generate-scene-briefs.ts`
 * (re-run whenever a template photo is added or changed).
 *
 * Why this exists (2026-09-26, measured): showing the image model the template
 * photo — which contains people — keeps pulling the result toward those people
 * (same-frame edit: right person 5/8 on a hard reference photo; "inspired-by"
 * with the template attached: 3/8). Giving it only a TEXT brief of the look,
 * with the person's own photo as the only image, got the right person 20/20
 * across 3 photos and 2 templates, with the template's look preserved (theme
 * score 4.00/5, same as faithful copies). So the brief must contain the
 * template's LOOK (place, lighting, palette, mood, outfits) and NEVER anything
 * about the people themselves — that is enforced below, not just requested.
 */
import { writeFileSync } from 'node:fs';
import { GoogleGenAI } from '@google/genai';

import { env } from '../src/env.js';
import { templateImageFor } from '../src/data/templateImages.js';

const TEMPLATE_IDS = [
  'goldenHour', 'cityLights', 'firstDance', 'beachSunset', 'rooftopNight', 'cherryBlossom',
  'winterWalk', 'neonNights', 'vintageParis', 'cyberDate', 'rainyWindow',
];

const BRIEF_PROMPT = `Write a SCENE BRIEF describing this photo's LOOK so a different person could be photographed in the same style. Plain text, 90-150 words. Include: the specific location and environment; the lighting, time of day and color palette; the mood and camera feel; and, for each person shown, their CLOTHING and ACCESSORIES in precise detail (garments, colors, fabrics, footwear, bags, jewelry), labeled "Woman's outfit:" and "Man's outfit:" by apparent gender (only label the people actually shown). STRICT: never describe anyone's face, hair, skin, age, ethnicity or body — only clothing and accessories.`;

// Words that would leak a stand-in's identity into the brief. Word-boundary
// matched so legit terms like "bangles" or "surface" are not flagged.
// Body/identity descriptions are flagged; garment details are not. "slim black tie" / "slim trousers"
// describe clothing (a real false positive we hit), so body-shape adjectives are only flagged when they
// describe a person: followed by a body/person noun ("slim build", "athletic woman").
const IDENTITY_WORDS = /\b(hair|hairstyle|face|faces|skin|eyes|brunette|blonde|redhead|bangs|curly|wavy|complexion|beard|mustache|moustache|ethnicity|young|elderly|teen|teenage)\b|\b(slim|slender|petite|curvy|muscular|athletic|stocky|heavyset|tall|short)\s+(build|figure|frame|body|physique|woman|man|person|model|waist|torso)\b/gi;

/** The model sometimes wraps the brief in markdown or a title; the brief is
 * prompt material, so strip that. */
const tidy = (text: string) => text.split('**').join('').replace(/^\s*#*\s*SCENE BRIEF:?\s*/i, '').split(/\s+/).join(' ').trim();

async function briefFor(client: GoogleGenAI, templateId: string): Promise<string> {
  const image = templateImageFor(templateId);
  if (!image) throw new Error(`no template photo for ${templateId}`);
  for (let attempt = 1; attempt <= 3; attempt++) {
    const response = await client.models.generateContent({
      model: env.GEMINI_JUDGE_MODEL,
      contents: [
        {
          role: 'user',
          parts: [
            { text: attempt === 1 ? BRIEF_PROMPT : `${BRIEF_PROMPT} Your previous attempt mentioned a person's physical features — describe ONLY the place, lighting, mood and clothing.` },
            { inlineData: { mimeType: image.mimeType, data: image.bytes.toString('base64') } },
          ],
        },
      ],
    });
    const brief = tidy(response.text ?? '');
    const leaks = brief.match(IDENTITY_WORDS);
    if (brief.length > 60 && !leaks) return brief;
    // Show the words in context: whether a flagged word is a body description or
    // just a garment detail ("slim tie") is a judgement call a human should see.
    const context = [...brief.matchAll(new RegExp(IDENTITY_WORDS.source, 'gi'))].map((m) => `...${brief.slice(Math.max(0, m.index! - 40), m.index! + m[0].length + 40)}...`);
    console.warn(`  ${templateId} attempt ${attempt}: ${leaks ? `identity words in context: ${context.join(' | ')}` : 'too short'}`);
  }
  throw new Error(`could not produce a clean brief for ${templateId}`);
}

const client = new GoogleGenAI({ apiKey: env.GEMINI_API_KEY });
const briefs: Record<string, string> = {};
for (const id of TEMPLATE_IDS) {
  briefs[id] = await briefFor(client, id);
  console.log(`${id}: ${briefs[id]}\n`);
}

const body = Object.entries(briefs).map(([id, text]) => `  ${id}: ${JSON.stringify(text)},`).join('\n');
writeFileSync(
  new URL('../src/data/sceneBriefs.ts', import.meta.url),
  `// AUTO-GENERATED by scripts/generate-scene-briefs.ts — do not edit by hand; re-run the script.\n// One text brief of each template's LOOK (place, lighting, mood, outfits). By construction it never\n// describes anyone's face/hair/body — see the script's header for why that matters.\nexport const SCENE_BRIEFS: Record<string, string> = {\n${body}\n};\n`,
);
console.log(`wrote src/data/sceneBriefs.ts (${TEMPLATE_IDS.length} briefs)`);
